<?php
/**
* Create a new form.
*
*/

/**
 * Implements hook_menu().
 *
 */
function restaurant_menu() {
  $items = array();
  $items['restaurant/add'] = array(
    'title' => 'Add a restaurant',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_add_rest'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['restaurants'] = array(
    'title' => 'Display, add, edit all restaurants',
    'page callback' => 'page_restaurants',
    'access callback' => TRUE,
  );
  return $items;
}

function form_add_rest($form, &$form_state) {

  $form['description'] = array(
    '#type' => 'item',
    '#title' => t('Enter the restaurant information below'),
  );
  $form['#attributes']['enctype'] = 'multipart/form-data';
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
  );
  $form['address'] = array(
    '#type' => 'textfield',
    '#title' => t('Address'),
  );
  $form['image'] = array(
    '#title' => t('Image'),
    '#type' => 'managed_file',
    '#description' => t('The uploaded image will be displayed on this page.'),
    '#default_value' => variable_get('image', ''),
    '#upload_location' => 'public://restaurant_images/',
  );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

//validation

/**
 * Submit function for form_add_rest.
 *
 * Adds a submit handler/function to our form to send a successful
 * completion message to the screen.
 */
function form_add_rest_submit($form, &$form_state) {
  $name = $form_state['values']['name'];
  $address = $form_state['values']['address'];
  $image = $form_state['values']['image'];
//insert into restaurants, values, etc
  $query = db_insert('restaurants')
    ->fields(array(
        'name' => $name,
        'address' => $address,
        'image' => $image,
        'timestamp' => REQUEST_TIME,
    ))
          ->execute();
  $file = file_load($form_state['values']['image']);
  $file->status = FILE_STATUS_PERMANENT;
  file_save($file);

  drupal_set_message(t('The form has been submitted.'));
}

function page_restaurants () {
  $sql= 'SELECT name, address, image from {restaurants} ORDER BY timestamp DESC';
  $result = db_query($sql);
  $header = array();
  $row =  array();
  $table_rows = array();
  $header = array('name', 'address','image');
  //output each result as a row
  foreach ($result as $row) {
    $image_object = file_load($row->image); //returns object
    $path = $image_object->uri; //gets path
    $table_rows[] = array(
      'data' => array(
          'name' => array(
              'data'=>$row->name,
              'class'=>'col-name',
          ),
          'address' => array(
              'data'=>$row->address,
              'class'=>'col-address',
          ),
          'image' => array(
              'data'=> theme('image',array('path' => $path)),
              'class'=>'col-image',
          ),
      )
  );
  }

return theme('table', array(
    'header' => $header,
    'rows' => $table_rows,
    'id' => 'restaurants',
    'class' => 'articles',));
}